### ISSUE TITLE
ModuleNotFoundError: No module named 'com.vesoft.nebula.connector'

### ISSUE THREAD

**Issue by porscheme** [vesoft-inc/nebula-spark-connector#46]
Spark Version: 3.2.1

We are using com.vesoft:nebula-spark-connector:3.0.0 in our pyspark application
We are getting ModuleNotFoundError error.
Thanks

Code snippet
```
conf = SparkConf()
conf.set("spark.jars.packages", "org.apache.hadoop:hadoop-azure:3.3.1,com.vesoft:nebula-spark-connector:3.0.0,com.vesoft:nebula-flink:3.0.0")
conf.set("spark.executor.extraClassPath", "com.vesoft:nebula-spark-connector:3.0.0,com.vesoft:nebula-flink:3.0.0")

# removed reset of the code for simplicity

spark = SparkSession.builder.config(conf=conf).getOrCreate()

# Prepare rdd
# removed reset of the code for simplicity

rdd.foreach(lambda f: process_blob(spark , f))

def process_blob(spark:SparkSession, parquet_file:str):
    from com.vesoft.nebula.connector import NebulaOptions 
    # removed reset of the code for simplicity
```

Error
```
Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 18 in stage 0.0 failed 4 times, most recent failure: Lost task 18.3 in stage 0.0 (TID 73) (10.201.37.17 executor 1): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/worker.py", line 619, in main
    process()
  File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/worker.py", line 609, in process
    out_iter = func(split_index, iterator)
  File "/usr/local/spark/python/pyspark/rdd.py", line 2918, in pipeline_func
  File "/usr/local/spark/python/pyspark/rdd.py", line 2918, in pipeline_func
  File "/usr/local/spark/python/pyspark/rdd.py", line 2918, in pipeline_func
  File "/usr/local/spark/python/pyspark/rdd.py", line 417, in func
  File "/usr/local/spark/python/pyspark/rdd.py", line 917, in processPartition
  File "/usr/local/spark/python/pyspark/util.py", line 74, in wrapper
  File "<ipython-input-8-fa91e09b3d08>", line 16, in <lambda>
  File "<ipython-input-12-4edd6eeef9a7>", line 3, in process_blob
ModuleNotFoundError: No module named 'com.vesoft.nebula.connector'

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:555)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:713)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:695)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:508)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:366)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:364)
	at org.apache.spark.InterruptibleIterator.to(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:358)
	at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:358)
	at org.apache.spark.InterruptibleIterator.toBuffer(InterruptibleIterator.scala:28)
	at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:345)
	at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:339)
	at org.apache.spark.InterruptibleIterator.toArray(InterruptibleIterator.scala:28)
	at org.apache.spark.rdd.RDD.$anonfun$collect$2(RDD.scala:1030)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2254)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by porscheme** [comment]
Does anyone use nebula-spark-connector from pyspark?

**Comment by Nicole00** [comment]
connector is not supported in pyspark.

**Comment by wey-gu** [comment]
@porscheme I didn't test with submitting of py file yet and only tested in pyspark REPL, while it should be equivalent.

Did you try replies in https://stackoverflow.com/questions/27698111/how-to-add-third-party-java-jar-files-for-use-in-pyspark ?

ref: https://github.com/vesoft-inc/nebula-spark-connector/pull/51/files
